config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :ad_urls
  resources :keywords do
    collection { post :import }
  end

  root :to => "keywords#index"

end

app/models/ad_url.rb
class AdUrl < ActiveRecord::Base
	belongs_to :keyword
	self.per_page = 20
end

app/controllers/ad_urls_controller.rb
class AdUrlsController < ApplicationController
  before_action :set_ad_url, only: [:show, :edit, :update, :destroy]

  # GET /ad_urls
  # GET /ad_urls.json
  def index
    @q = AdUrl.ransack(params[:q])
    @ad_urls = @q.result.page(params[:page])
    # @ad_urls = AdUrl.all
  end

  # GET /ad_urls/1
  # GET /ad_urls/1.json
  def show
  end

  # GET /ad_urls/new
  def new
    @ad_url = AdUrl.new
  end

  # GET /ad_urls/1/edit
  def edit
  end

  # POST /ad_urls
  # POST /ad_urls.json
  def create
    @ad_url = AdUrl.new(ad_url_params)

    respond_to do |format|
      if @ad_url.save
        format.html { redirect_to @ad_url, notice: 'Ad url was successfully created.' }
        format.json { render :show, status: :created, location: @ad_url }
      else
        format.html { render :new }
        format.json { render json: @ad_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ad_urls/1
  # PATCH/PUT /ad_urls/1.json
  def update
    respond_to do |format|
      if @ad_url.update(ad_url_params)
        format.html { redirect_to @ad_url, notice: 'Ad url was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad_url }
      else
        format.html { render :edit }
        format.json { render json: @ad_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ad_urls/1
  # DELETE /ad_urls/1.json
  def destroy
    @ad_url.destroy
    respond_to do |format|
      format.html { redirect_to ad_urls_url, notice: 'Ad url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad_url
      @ad_url = AdUrl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_url_params
      params.require(:ad_url).permit(:link, :position, :is_ad)
    end
end

app/helpers/ad_urls_helper.rb
module AdUrlsHelper
end

app/views/ad_urls/_form.html.erb
<%= form_for(@ad_url) do |f| %>
  <% if @ad_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad_url.errors.count, "error") %> prohibited this ad_url from being saved:</h2>

      <ul>
      <% @ad_url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :is_ad %><br>
    <%= f.check_box :is_ad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ad_urls/edit.html.erb
<h1>Editing Ad Url</h1>

<%= render 'form' %>

<%= link_to 'Show', @ad_url %> |
<%= link_to 'Back', ad_urls_path %>

app/views/ad_urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ad Urls</h1>

<%= search_form_for @q do |f| %>

  # Search if the name field contains...
  <%= f.label :link_cont %>
  <%= f.search_field :link_cont %>
  <%= f.label :is_ad_eq %>
  <%= f.select :is_ad_eq, [['Yes', 1], ['No', 0]], {include_blank: 'All'}, {class: 'selectpicker chosen-select'} %>
  <%= f.label :position_eq %>
  <%= f.select :position_eq, [['Top', 'top'], ['Right', 'right'], ['Center', 'center']], {include_blank: 'All'}, {class: 'selectpicker chosen-select'} %>

  <%= f.submit %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Position</th>
      <th>Is ad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ad_urls.each do |ad_url| %>
      <tr>
        <td><%= link_to truncate(ad_url.link, :length => 50), ad_url.link %></td>
        <td><%= ad_url.position %></td>
        <td><%= ad_url.is_ad %></td>
        <td><%= link_to 'Show', ad_url %></td>
        <td><%= link_to 'Edit', edit_ad_url_path(ad_url) %></td>
        <td><%= link_to 'Destroy', ad_url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  <%= will_paginate @ad_urls %>
</table>

<br>

<%= link_to 'Keywords', keywords_path %>

<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>

app/views/ad_urls/new.html.erb
<h1>New Ad Url</h1>

<%= render 'form' %>

<%= link_to 'Back', ad_urls_path %>

app/views/ad_urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @ad_url.link %>
</p>

<p>
  <strong>Position:</strong>
  <%= @ad_url.position %>
</p>

<p>
  <strong>Is ad:</strong>
  <%= @ad_url.is_ad %>
</p>

<%= link_to 'Edit', edit_ad_url_path(@ad_url) %> |
<%= link_to 'Back', ad_urls_path %>