config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :ad_urls
  resources :keywords do
    collection { post :import }
  end

  root :to => "keywords#index"

end

app/models/keyword.rb
require 'roo'
require 'net/http'
require 'httpclient'
require 'uri'


class Keyword < ActiveRecord::Base
	has_many :ad_urls, dependent: :destroy

	validates :word, presence: true
	after_create :delay_search_on_google

	attr_accessor :html_page

	def self.import(file)
		spreadsheet = open_spreadsheet(file)
		header = spreadsheet.row(1)
		(1..spreadsheet.last_row).each do |i|
			row = spreadsheet.row(i)
			row.each do |word|
				if word
					keyword = Keyword.find_or_create_by(word: word)
				end
			end
		end
	end

	def self.open_spreadsheet(file)
		case File.extname(file.original_filename)
		when ".csv" then Roo::CSV.new(file.path, csv_options: {encoding: "iso-8859-1:utf-8"})
		else raise "Unknown file type: #{file.original_filename}"
		end
	end

	def delay_search_on_google
		self.delay.search_on_google
	end

	def search_on_google
		uri = URI.parse( "http://www.google.co.uk/search" )
		params = {'q'=> self.word}

		http = Net::HTTP.new(uri.host, uri.port) 
		request = Net::HTTP::Get.new(uri.path) 
		request.set_form_data( params )

		# instantiate a new Request object
		request = Net::HTTP::Get.new( uri.path+ '?' + request.body ) 

		response = http.request(request)
		self.html_page = response.read_body
		# self.html_page.force_encoding("ISO-8859-1").encode("UTF-8")
		# self.save!
		self.parsing_html
	end

	def store_url(node, ele_pos, ad_boolean)
		link = node.attributes["href"].value
		if link.match(/http.*/)
			page_url = link.match(/http.*/)[0]
			puts page_url
			ad_url = self.ad_urls.find_or_create_by(link: page_url)
			ad_url.update(position: ele_pos, is_ad: ad_boolean)
		end
	end

	def parsing_html
		html_doc = Nokogiri::HTML(self.html_page)
		# Num Results
		num_results_ele = html_doc.css("#resultStats")
		num_results_str = num_results_ele[0].children[0].to_s
		num_results = num_results_str.gsub(/[^\d]/, '').to_i
		self.total_results = num_results
		self.save!
		# Nodes Results
		top_ads_nodes = html_doc.css("#center_col li.ads-ad h3 a")
		right_ads_nodes = html_doc.css("#rhs_block li.ads-ad h3 a")
		non_ads_nodes = html_doc.css("#ires li h3 a")

		top_ads_nodes.each do |node|
			store_url(node, "top", true)
		end

		right_ads_nodes.each do |node|
			store_url(node, "right", true)
		end

		non_ads_nodes.each do |node|
			store_url(node, "center", false)
		end
	end

	# Keyword.search_google("ruby rails")
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :set_keyword, only: [:show, :edit, :update, :destroy]

  # GET /keywords
  # GET /keywords.json
  def index
    @keywords = Keyword.all
  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
  end

  # GET /keywords/new
  def new
    @keyword = Keyword.new
  end

  # GET /keywords/1/edit
  def edit
  end

  # POST /keywords
  # POST /keywords.json
  def create
    @keyword = Keyword.new(keyword_params)

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: 'Keyword was successfully created.' }
        format.json { render :show, status: :created, location: @keyword }
      else
        format.html { render :new }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keywords/1
  # PATCH/PUT /keywords/1.json
  def update
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { render :show, status: :ok, location: @keyword }
      else
        format.html { render :edit }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword.destroy
    respond_to do |format|
      format.html { redirect_to keywords_url, notice: 'Keyword was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Import CSV File
  def import
    Keyword.import(params[:file])
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Keywords imported.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def keyword_params
      params.require(:keyword).permit(:word, :page)
    end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.erb
<%= form_for(@keyword) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% @keyword.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keywords/edit.html.erb
<h1>Editing Keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Keywords</h1>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th>Total Results</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @keywords.each do |keyword| %>
      <tr>
        <td><%= keyword.word %></td>
        <td><%= keyword.total_results %></td>
        <td><%= link_to 'Show', keyword %></td>
        <td><%= link_to 'Edit', edit_keyword_path(keyword) %></td>
        <td><%= link_to 'Destroy', keyword, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Keyword', new_keyword_path %>
<br>
<h1>
  <%= link_to 'View Report', ad_urls_path %>
</h1>

<h2>Import Products</h2>

<%= form_tag import_keywords_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/keywords/new.html.erb
<h1>New Keyword</h1>

<%= render 'form' %>

<%= link_to 'Back', keywords_path %>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @keyword.word %>
</p>

<p>
  <strong>Page:</strong>
  <%= @keyword.page %>
</p>

<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>